openapi: 3.0.3
info:
  title: 'Bizmoto Wallet'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/v1/rest/transfer:
    post:
      summary: "Execute the fund movements (credits and debits) required to\ncomplete the transaction associated to the provided Ref. No."
      operationId: executeTheFundMovementscreditsAndDebitsRequiredTocompleteTheTransactionAssociatedToTheProvidedRefNo
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_ACCESS_TOKEN}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Source:
                  type: number
                  description: 'The source Account Number.'
                  example: 10010586384.0
                Target:
                  type: number
                  description: 'The target Account Number.'
                  example: 10010645288.0
                Amount:
                  type: number
                  description: 'The amount to be transferred.'
                  example: 245.5
                Fee:
                  type: number
                  description: 'The transaction''s total fee (will be sent to the default Fee Account). If there are multiple fee recipients, leave this blank and fill out the "Accounts" parameter.'
                  example: 10.0
                Accounts:
                  type: array
                  description: 'The Fee Accounts and respective fees for each account. Example: {"0060001": 15.2, "0070001": 12.8}.'
                  example:
                    - 60001.0
                  items:
                    type: number
              required:
                - Source
                - Target
                - Amount
                - Accounts
  /api/v1/rest/reverseTransaction:
    post:
      summary: 'Reverse/refund a transaction that has been executed'
      operationId: reverserefundATransactionThatHasBeenExecuted
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_ACCESS_TOKEN}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                RefNum:
                  type: integer
                  description: "The journal record's Reference Number."
                  example: 168742
              required:
                - RefNum
  /api/v1/rest/balanceinquiry:
    post:
      summary: 'Find the balance for the given Account number'
      operationId: findTheBalanceForTheGivenAccountNumber
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_ACCESS_TOKEN}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                AccountNo:
                  type: number
                  description: 'The Account Number for which the balance is being fetched.'
                  example: 10010586384.0
              required:
                - AccountNo
  '/api/v2/wallet/balance/{account_no}':
    get:
      summary: "Fetch the current User's Wallet Balance(s)"
      operationId: fetchTheCurrentUsersWalletBalances
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_ACCESS_TOKEN}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: 401
                  title: Unauthorized
                  type: 'https://www.rfc-editor.org/rfc/rfc9110.html'
                  message: 'You are unauthenticated and therefore unauthorized to access this resource.'
                  details: 'The access token provided is either expired or invalid.'
                  _links:
                    self:
                      href: 'http://localhost/api/v2/wallet/balance/et'
                properties:
                  status:
                    type: integer
                    example: 401
                  title:
                    type: string
                    example: Unauthorized
                  type:
                    type: string
                    example: 'https://www.rfc-editor.org/rfc/rfc9110.html'
                  message:
                    type: string
                    example: 'You are unauthenticated and therefore unauthorized to access this resource.'
                  details:
                    type: string
                    example: 'The access token provided is either expired or invalid.'
                  _links:
                    type: object
                    properties:
                      self:
                        type: object
                        properties:
                          href:
                            type: string
                            example: 'http://localhost/api/v2/wallet/balance/et'
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: account_no
        description: 'Optional parameter.'
        required: true
        schema:
          type: string
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: et
  '/api/v2/wallet/{account_no}':
    get:
      summary: "Fetch details of a User's specific Wallet"
      operationId: fetchDetailsOfAUsersSpecificWallet
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_ACCESS_TOKEN}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: 401
                  title: Unauthorized
                  type: 'https://www.rfc-editor.org/rfc/rfc9110.html'
                  message: 'You are unauthenticated and therefore unauthorized to access this resource.'
                  details: 'The access token provided is either expired or invalid.'
                  _links:
                    self:
                      href: 'http://localhost/api/v2/wallet/voluptate'
                properties:
                  status:
                    type: integer
                    example: 401
                  title:
                    type: string
                    example: Unauthorized
                  type:
                    type: string
                    example: 'https://www.rfc-editor.org/rfc/rfc9110.html'
                  message:
                    type: string
                    example: 'You are unauthenticated and therefore unauthorized to access this resource.'
                  details:
                    type: string
                    example: 'The access token provided is either expired or invalid.'
                  _links:
                    type: object
                    properties:
                      self:
                        type: object
                        properties:
                          href:
                            type: string
                            example: 'http://localhost/api/v2/wallet/voluptate'
      tags:
        - Endpoints
    parameters:
      -
        in: path
        name: account_no
        description: ''
        example: voluptate
        required: true
        schema:
          type: string
  /api/v2/wallet:
    get:
      summary: 'Fetch details of all Wallets that belong to User'
      operationId: fetchDetailsOfAllWalletsThatBelongToUser
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_ACCESS_TOKEN}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: 401
                  title: Unauthorized
                  type: 'https://www.rfc-editor.org/rfc/rfc9110.html'
                  message: 'You are unauthenticated and therefore unauthorized to access this resource.'
                  details: 'The access token provided is either expired or invalid.'
                  _links:
                    self:
                      href: 'http://localhost/api/v2/wallet'
                properties:
                  status:
                    type: integer
                    example: 401
                  title:
                    type: string
                    example: Unauthorized
                  type:
                    type: string
                    example: 'https://www.rfc-editor.org/rfc/rfc9110.html'
                  message:
                    type: string
                    example: 'You are unauthenticated and therefore unauthorized to access this resource.'
                  details:
                    type: string
                    example: 'The access token provided is either expired or invalid.'
                  _links:
                    type: object
                    properties:
                      self:
                        type: object
                        properties:
                          href:
                            type: string
                            example: 'http://localhost/api/v2/wallet'
      tags:
        - Endpoints
  /api/v2/transaction/transfer:
    post:
      summary: 'Execute the fund movements of a given Bizmoto Transaction'
      operationId: executeTheFundMovementsOfAGivenBizmotoTransaction
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_ACCESS_TOKEN}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction_uuid:
                  type: string
                  description: 'Must be a valid UUID.'
                  example: 729a1f81-a73b-32cb-8f17-a304781dd491
              required:
                - transaction_uuid
  /api/v2/transaction/reverse:
    post:
      summary: 'Reverse/refund a transaction that has been executed'
      operationId: reverserefundATransactionThatHasBeenExecuted
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_ACCESS_TOKEN}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction_uuid:
                  type: string
                  description: 'Must be a valid UUID.'
                  example: e7a98c3f-405a-3dd2-bcd0-d4db547ecf7c
              required:
                - transaction_uuid
  /api/v2/transaction:
    get:
      summary: "Fetch all Wallet Journal Records that belong\nto a Transaction reference number"
      operationId: fetchAllWalletJournalRecordsThatBelongtoATransactionReferenceNumber
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_ACCESS_TOKEN}'
          schema:
            type: string
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  status: 401
                  title: Unauthorized
                  type: 'https://www.rfc-editor.org/rfc/rfc9110.html'
                  message: 'You are unauthenticated and therefore unauthorized to access this resource.'
                  details: 'The access token provided is either expired or invalid.'
                  _links:
                    self:
                      href: 'http://localhost/api/v2/transaction'
                properties:
                  status:
                    type: integer
                    example: 401
                  title:
                    type: string
                    example: Unauthorized
                  type:
                    type: string
                    example: 'https://www.rfc-editor.org/rfc/rfc9110.html'
                  message:
                    type: string
                    example: 'You are unauthenticated and therefore unauthorized to access this resource.'
                  details:
                    type: string
                    example: 'The access token provided is either expired or invalid.'
                  _links:
                    type: object
                    properties:
                      self:
                        type: object
                        properties:
                          href:
                            type: string
                            example: 'http://localhost/api/v2/transaction'
      tags:
        - Endpoints
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                transaction_uuid:
                  type: string
                  description: 'Must be a valid UUID.'
                  example: 7c65daa7-cb86-3e04-baa4-4ea089abd534
                date_start:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-02-03T02:10:39'
                date_end:
                  type: string
                  description: 'Must be a valid date.'
                  example: '2023-02-03T02:10:39'
                include_debits:
                  type: boolean
                  description: ''
                  example: false
                include_credits:
                  type: boolean
                  description: ''
                  example: false
tags:
  -
    name: Endpoints
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
